"""
Query expansion for SuperSearch.

Given a user query, generate 2-3 additional variants that cover different
angles (synonyms, narrower/broader phrasing). Variants are generated by a
local model via Ollama. Failure is non-fatal: callers get an empty list back
and should proceed with the original query only.
"""

from typing import List

import httpx


EXPAND_SYSTEM = """## TASK
Generate 2-3 alternative phrasings of a search query. Each variant should
cover a DIFFERENT angle (synonyms, narrower, broader, related terms).

## CONSTRAINTS
- Return 2-3 variants. NOT more, NOT fewer.
- Each variant on its own line. No numbering, no bullets, no explanation.
- Variants must be DIFFERENT enough to surface different results.
- Keep variants short (3-10 words each).
- Stay on-topic. NOT unrelated queries.

## FORMAT
variant 1
variant 2
variant 3"""


def _parse_variants(text: str, original: str, max_variants: int = 3) -> List[str]:
    """Parse model output into a clean deduped list of variants."""
    variants: List[str] = []
    seen = {original.strip().lower()}
    for line in text.splitlines():
        v = line.strip().lstrip("-*0123456789. )").strip()
        if not v:
            continue
        # Drop quotes if the model wrapped the variant
        v = v.strip('"').strip("'").strip()
        if not v:
            continue
        key = v.lower()
        if key in seen:
            continue
        seen.add(key)
        variants.append(v)
        if len(variants) >= max_variants:
            break
    return variants


def expand_query(
    query: str,
    model: str = "qwen3:14b",
    ollama_url: str = "http://localhost:11434",
    max_variants: int = 3,
    timeout: float = 20.0,
) -> List[str]:
    """Return up to max_variants alternative phrasings of the query.

    On any error or timeout, returns []. Never raises.
    """
    if not query or not query.strip():
        return []
    try:
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(
                f"{ollama_url}/api/chat",
                json={
                    "model": model,
                    "messages": [
                        {"role": "system", "content": EXPAND_SYSTEM},
                        {"role": "user", "content": f"Original query: {query}"},
                    ],
                    "stream": False,
                    "options": {"temperature": 0.2, "num_predict": 200},
                },
            )
            if resp.status_code != 200:
                return []
            data = resp.json()
            content = data.get("message", {}).get("content", "")
            return _parse_variants(content, query, max_variants=max_variants)
    except Exception:
        return []


def dedupe_results(results_lists: List[list]) -> list:
    """Merge and dedupe SearchResult-shaped items across variant runs by URL."""
    seen = set()
    merged = []
    for results in results_lists:
        for r in results:
            url = getattr(r, "url", None) or (r.get("url") if isinstance(r, dict) else None)
            if not url or url in seen:
                continue
            seen.add(url)
            merged.append(r)
    return merged
